-- Create grains_bcr table for BCR price cache
CREATE TABLE IF NOT EXISTS granos_bcr (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_bcr TEXT,
  granos JSONB NOT NULL,
  fetched_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE granos_bcr ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read on granos_bcr" ON granos_bcr
  FOR SELECT USING (true);

-- Allow service role write (for cron job)
CREATE POLICY "Allow service role write on granos_bcr" ON granos_bcr
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow service role delete on granos_bcr" ON granos_bcr
  FOR DELETE USING (true);